apache/answer

docker-compose.yaml

Modify default dir_name when docker-compose start

---

CONTRIBUTING.md
INSTALL.md
README.md
ui/src/i18n/locales/en.json
ui/src/i18n/locales/zh_CN.json

Greetings, folks. I found your project today, and while reviewing it I found various textual content that seemed could be tweaked just a bit. I hope it's ok that I just propose these changes as a PR, without opening an issue. Some maintainers would happily accept such proposed changes without need of discussion. If you prefer to discuss anything, ok.  Same with if you opt to not accept the PR. 
Just trying to help. I would hope to turn my attention next to the docs and its repo.

Refine text content

---

ui/src/utils/request.ts

- error key of object
- front-end & back-end same domain, use can add new env variable have value is domain front-end and update into baseURL

update baseUrl -> baseURL in file request in line 14

---

ui/src/utils/guard.ts
ui/src/utils/localize.ts

* Getting dynamic language files to work correctly
* Keeping the local cache of language files up to date

fix(i18n): Fixes for multilingual file loading and updating issues

---

ui/src/pages/Users/index.tsx

fix: fix avatar squash in users page

---

ui/src/pages/Admin/Flags/index.tsx

* Fix the font size of the BaseUserCard component in the Flags page

fix(Flags): 

---

internal/service/question_common/question.go
internal/service/question_service.go

fix typos of update in question_common.go

fix:misspelling correction of words

---

i18n/de_DE.yaml
i18n/es_ES.yaml
i18n/fr_FR.yaml
i18n/i18n.yaml
i18n/id_ID.yaml
i18n/it_IT.yaml
i18n/ja_JP.yaml
i18n/ko_KR.yaml
i18n/pt_PT.yaml
i18n/ru_RU.yaml
i18n/sk_SK.yaml
i18n/tr_TR.yaml
i18n/vi_VN.yaml
i18n/zh_CN.yaml
i18n/zh_TW.yaml
internal/repo/auth/auth.go
internal/repo/role/user_role_rel_repo.go
internal/service/auth/auth.go
internal/service/user_admin/user_backyard.go
pkg/converter/markdown.go

`"github.com/yuin/goldmark/renderer/html"` was being imported twice.

pkg/converter: fix redundant import

---

.asf.yaml

This fixes https://github.com/apache/incubator-answer/issues/583.

chore: update website url

---

ui/src/pages/Search/components/SearchItem/index.tsx
ui/src/pages/Users/Personal/components/Answers/index.tsx
ui/src/pages/Users/Personal/components/Comments/index.tsx
ui/src/pages/Users/Personal/components/DefaultList/index.tsx
ui/src/pages/Users/Personal/components/Reputation/index.tsx
ui/src/pages/Users/Personal/components/TopList/index.tsx
ui/src/pages/Users/Personal/components/Votes/index.tsx

use `Link` instead of `<a>` tag to prevent wrong link in this situation
www.xxx.com/answer/

fix: 🐛 link

---

i18n/de_DE.yaml

Fix time format problem in **de-DE**

fix(i18n): fix time format in de-DE

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/enhancement_request.md

* update: github issue template

update: github issue template

---

.goreleaser.yaml
internal/service/uploader/upload.go
pkg/checker/file_type.go
ui/src/components/TagSelector/index.tsx

fix: incomplete text display when pasting text into the tags field

---

ui/src/pages/Search/components/SearchItem/index.tsx

fix: only display vote number and acceptance if necessary

---

i18n/en_US.yaml
i18n/zh_CN.yaml
internal/schema/question_schema.go
ui/src/common/constants.ts
ui/src/pages/Admin/Questions/components/Action/index.tsx
ui/src/pages/Admin/Questions/index.tsx

feat: support list and unlist in admin contents page for questions

---

.goreleaser.yaml
internal/service/uploader/upload.go
pkg/checker/file_type.go
ui/src/behaviour/clicks.tsx
ui/src/pages/Users/Register/components/SignUpForm/index.tsx

To enhance reusability - moved this behavior outside so that other components can reuse this.
Testing Everything is running smooth after changes.

refactor Changes - moved legal clicks outside of signup

---

.goreleaser.yaml
internal/service/uploader/upload.go
pkg/checker/file_type.go
ui/src/hooks/useToast/index.tsx

fix(toast): align to the center with actual element width

---

ui/src/components/Comment/index.tsx

fixes https://github.com/apache/incubator-answer/issues/887

fix bug where no error message is showing when comment length exceeds max length when updating comment

---

ui/src/router/index.tsx
ui/src/utils/pluginKit/index.ts
ui/src/utils/pluginKit/utils.ts

This PR extends the type of plugin and supports route type plugin.

feat(ui): Support route types in plugin system

---

i18n/en_US.yaml
i18n/zh_CN.yaml

fix: missing btns.more in i18n

---

ui/src/components/PageTags/index.tsx

feat: adding social media meta tags

---

i18n/ko_KR.yaml

compared to en_US, I've revised the modifications you requested
Apart from this, I am going to do it again through crowdin.

ko_KR update

---

ui/src/components/Comment/index.tsx
ui/src/components/Modal/LoginToContinueModal.tsx
ui/src/components/Modal/login.scss
ui/src/pages/Questions/Detail/components/Reactions/index.tsx

fix: loginToContinueModal z-index error

---

i18n/af_ZA.yaml
i18n/ar_SA.yaml
i18n/az_AZ.yaml
i18n/bal_BA.yaml
i18n/ban_ID.yaml
i18n/bn_BD.yaml
i18n/bs_BA.yaml
i18n/ca_ES.yaml
i18n/cs_CZ.yaml
i18n/cy_GB.yaml
i18n/da_DK.yaml
i18n/el_GR.yaml
i18n/en_US.yaml
i18n/fi_FI.yaml
i18n/he_IL.yaml
i18n/hi_IN.yaml
i18n/hu_HU.yaml
i18n/hy_AM.yaml
i18n/ja_JP.yaml
i18n/nl_NL.yaml
i18n/no_NO.yaml
i18n/sq_AL.yaml
i18n/sr_SP.yaml
i18n/sv_SE.yaml
i18n/tr_TR.yaml
i18n/vi_VN.yaml
i18n/zh_CN.yaml
i18n/zh_TW.yaml
ui/src/pages/Users/Register/components/SignUpForm/index.tsx

fix #977 .
* added validation logic (referred backend logic) before sending request.
* added translations.

fix: incomplete display of error message alerts on registration page

---

pkg/converter/markdown.go
ui/src/components/Mentions/index.tsx
ui/src/utils/common.ts

fix: When @ someone, markdown render error

---

internal/controller/template_controller.go
internal/router/ui.go
plugin/cdn.go
plugin/plugin.go

feat(cdn-plugin): add cdn plugin

---

internal/migrations/migrations.go
internal/migrations/v21.go

fix(update): fix update to v1.3.6

fix(update): fix update to v1.3.6

---

ui/src/pages/Questions/Detail/components/Reactions/index.tsx

fix(ui/src/pages/Questions/Detail/components/Reactions/index.tsx): change in the display for mobile phones of the reactions #1064

Change in the display of emoticons

---

ui/src/pages/Install/components/FirstStep/index.tsx
ui/src/pages/Install/index.tsx

fix https://github.com/apache/incubator-answer/issues/1077#issuecomment-2342970839

feat: install page support i18n

---

i18n/en_US.yaml
i18n/zh_CN.yaml
ui/src/pages/Users/Personal/components/Overview/index.tsx

style: Improve the display of personal page when there is no information

---

cmd/wire_gen.go
internal/controller/template_controller.go
ui/template/hot-question.html
ui/template/question-detail.html
ui/template/question.html
ui/template/related-question.html

feat: Support related and hot questions template

---

internal/controller/template_controller.go

fix: resolve 404 error on Tags static page

---

ui/src/pages/Admin/Dashboard/components/HealthStatus/index.tsx

fix: display timezone on Dashboard when set to UTC

---

i18n/en_US.yaml
i18n/zh_CN.yaml
ui/src/pages/Tags/Detail/index.tsx

fix: Tag summary display is not as expected on tag detail page

---

ui/src/pages/Tags/index.tsx

fix: Searching for tags after paging brings up 404

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/pages/Install/components/FourthStep/index.tsx

Reverts apache/answer#1234
According to: 
https://github.com/apache/answer/issues/1228#issuecomment-2655545320

Revert "feat: add password hide show logic for init server"
