ui/package.json, ui/scripts/preinstall.js
This PR is used to prompt when using yarn or npm or cnpm to install dependencies, only pnpm is supported
But there is a bug when using npm to install: 
the execution of preinstall is after install
so when this prompt is displayed, the dependent packages have already been installed.
has another solution is:
`"preinstall": "npx only-allow pnpm"`, it's use only-allow package be supported by pnpm
This solution has the same bug as above
------------------------------------------
这个 PR 用来在使用 yarn 或 npm 或 cnpm 安装依赖时，进行提示只支持 pnpm
但使用 npm 安装时有一个 bug：
preinstall 的执行是在 install 安装之后
所以当出现这个提示的时候，依赖包其实已经安装好了。（只能起到提示的作用）
还有一个方案是使用 pnpm 提供的包 (only-allow)[https://github.com/pnpm/only-allow]：
```js
// package.json
"scripts": {
"preinstall": "npx only-allow pnpm"
}
```
这个方案也会出现上面说到的 npm 的 bug
=> Only allow use pnpm

.github/workflows/uffizzi-build.yml, .github/workflows/uffizzi-preview.yml, docker-compose.uffizzi.yml
This PR is adding support for **preview environments for PR events** (opened, sync'ed, reopened, etc) powered by [Uffizzi](https://www.uffizzi.com/). 
This PR is using GHA workflows to build and provision the preview environments. Utilizing docker-compose examples from **answer's** repo, the PR uses `docker-compose.uffizzi.yml` to build `answer` from source - this makes sure the latest changes are reflected in the preview. The docker-compose also includes a MySQL instance to persist data. 
Once a PR event is triggered — _PR opened, PR synced, review requested_ — the build workflow will build the image, and the preview workflow will either spin up a new preview or update an existing preview. The previews are ephemeral — so they live for only as long as needed. 
A comment will be posted on …
=> Preview Environment for PRs on Answer

i18n/af_ZA.yaml, i18n/ar_SA.yaml, i18n/ca_ES.yaml, i18n/cs_CZ.yaml, i18n/cy_GB.yaml, i18n/da_DK.yaml, i18n/el_GR.yaml, i18n/en_US.yaml, i18n/fi_FI.yaml, i18n/he_IL.yaml, i18n/hu_HU.yaml, i18n/id_ID.yaml, i18n/it_IT.yaml, i18n/ko_KR.yaml, i18n/nl_NL.yaml, i18n/no_NO.yaml, i18n/pt_BR.yaml, i18n/pt_PT.yaml, i18n/ro_RO.yaml, i18n/ru_RU.yaml, i18n/sk_SK.yaml, i18n/sr_SP.yaml, i18n/sv_SE.yaml, i18n/tr_TR.yaml, i18n/uk_UA.yaml, i18n/vi_VN.yaml, i18n/zh_CN.yaml, i18n/zh_TW.yaml, ui/src/pages/Questions/EditAnswer/index.scss
1. I think this editor maybe change 
Reproduction steps: Answer the question, click the edit button to enter the editing interface, and then display.
2. create user max display_name is 4 - 30 but message is 3 -30
=> fix: answer edit style

ui/src/pages/Tags/Edit/index.tsx
=> fix: can't show tag description in tag edit page

internal/repo/question/question_repo.go, internal/repo/search_common/search_repo.go, internal/repo/tag/tag_repo.go, internal/schema/search_schema.go, internal/service/question_common/question.go, internal/service/question_service.go, internal/service/search_common/search.go, internal/service/search_parser/search_parser.go, internal/service/tag_common/tag_common.go, pkg/converter/array.go, plugin/search.go
=> fix: questions with synonym tags do not show under the origin tag

ui/src/pages/Questions/EditAnswer/index.tsx
fix #713 .
After changing to `useEffect`, the issue was resolved. I don't know why we use `useLayoutEffect`. Pls let me know if something I missed.
=> fix: the answer's content in edit answer page disappears

internal/repo/answer/answer_repo.go
Resolve issue with MeiliSearch plugin not updating new answers
Fixes bug reported in Issue #738
Description:
Addressed the issue where new answers were not updating in MeiliSearch when using the MeiliSearch plugin (also probabely for other search plugins). The problem was traced back to a pointer-related error in answer_repo.go (line 417). During debugging, an error message "a pointer to a pointer is not allowed" was encountered.
Debugging Information:
While investigating, I identified a potential problem with the initialization of the question instance. To mitigate the issue, I modified the initialization process.
##738 #bugfix
=> fix: resolve MeiliSearch plugin not updating new answers

internal/schema/search_schema.go, internal/schema/search_schema_test.go
Close #819 . Need @LinkinStars 's help to review if we could remove replacing '-' with ' ' for search, or any better solution.
=> fix: can't search username with '-' character

ui/src/components/SideNav/index.scss, ui/src/pages/Layout/index.tsx, ui/src/pages/SideNavLayout/index.tsx
This PR aims to solve the problem of flex layout not meeting expectations in certain scenarios.
* Refactored the flex layout rules to enhance code readability and maintainability.
* Fixed the issue where the flex layout was not working correctly in specific scenarios.
=> refactor(ui): Refactor flex layout

ui/src/components/Comment/index.tsx
fix #900 , the root cause should be that sometimes, the comments data have not been received by client and there's no corresponding element.
=> fix: sometimes the comment link in the notification cannot be highlighted after clicking

ui/src/components/Tag/index.tsx
#961 
The reason for the error handling of escaped characters in the `tag component` is due to the redundant use of the encodeURIComponent function when passing the slug parameter. The `slugName` has already been processed in `pathFactory.tagLanding`, so it does not need to be processed again when passing parameters.
I'm sorry for the incorrect operations on my Git.
Thanks for your help @LinkinStars @shuashuai
=> fix: Chinese character tag bug

licenserc.toml, ui/src/pages/Install/index.tsx
Support switching databases to display the relevant database configurations during the initial installation
When switching to Mysql, use:
Username: root
Password: root
Database host: db:3306
When switching to Postgres, use
Username: postgres
Password: postgres
Database host: db:5432
=> support to display the relevant database info when switching databases

ui/src/components/TagSelector/index.tsx
Fix for #1118 
Fixed:
- Stop hammering the backend with every tag search key stroke ( 400 ms `debounce`)
Fixing:
- Use old state till the debounce results come back.
=> [WIP #1118] fix: add 400 second tag search debounce

docs/docs.go, docs/swagger.json, docs/swagger.yaml, i18n/en_US.yaml, i18n/zh_CN.yaml, internal/base/constant/user.go, internal/controller_admin/user_backyard_controller.go, internal/repo/activity/vote_repo.go, internal/repo/answer/answer_repo.go, internal/repo/question/question_repo.go, internal/repo/user/user_backyard_repo.go, internal/router/answer_api_router.go, internal/schema/backyard_user_schema.go, internal/service/answer_common/answer.go, internal/service/question_common/question.go, internal/service/user_admin/user_backyard.go, internal/service/user_common/user.go, ui/src/pages/Admin/Answers/index.tsx, ui/src/pages/Admin/Questions/index.tsx, ui/src/pages/Admin/Users/index.tsx, ui/src/services/common.ts
=> feat: Add permanently delete

ui/package.json, ui/pnpm-lock.yaml, ui/src/pages/Install/components/FourthStep/index.tsx
Hi team,
I have implemented the eye icon (👀) feature that allows users to toggle password visibility during the installation process. Please review the changes. Thank you. 
Close #1228
=> feat: add password hide show logic for init server

ui/src/pages/Install/index.tsx
When switching the language during installation, the language in the store was not updated, which caused the Accept-Language in the request interceptor to always be set as the default language.
=> fix(install): update language in logged user info store

i18n/en_US.yaml, i18n/zh_CN.yaml, internal/install/install_req.go, pkg/checker/username.go, ui/src/pages/Install/components/FourthStep/index.tsx
=> fix: update admin name validation

ui/src/pages/Questions/Detail/index.scss
Close #1258 .
Changed to `gray-800` for dark theme, cause `900` is quite invisible.
=> fix(ui): correct hover background color for dark theme in reaction button

ui/src/pages/Questions/Detail/components/Reactions/index.tsx, ui/src/pages/Questions/Detail/index.scss
Fix #1258 .
Used the default dark variant for button. Pls let me if it works or not. Thanks!
hover.
=> fix(ui): implement dark mode support for reaction buttons

i18n/en_US.yaml, i18n/zh_CN.yaml, ui/src/components/Header/index.tsx, ui/src/pages/Search/components/SearchHead/index.tsx, ui/src/pages/Search/index.tsx
=> feat: add loading state for counts display in search results
